# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffpane < Formula
  desc "Real-time TUI diff viewer for AI coding agents"
  homepage "https://github.com/Astro-Han/diffpane"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Astro-Han/diffpane/releases/download/v0.3.0/diffpane_0.3.0_darwin_amd64.tar.gz"
    sha256 "c939ecdca801ae8d25a70241e28b209c7bc808635f7a1c2be749d238a4249194"

    define_method(:install) do
      bin.install "diffpane"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Astro-Han/diffpane/releases/download/v0.3.0/diffpane_0.3.0_darwin_arm64.tar.gz"
    sha256 "104247e2cb2849f1f57cd0da870012771462140de07f308181269ada1a9915ed"

    define_method(:install) do
      bin.install "diffpane"
    end
  end
end
