# typed: false
# frozen_string_literal: true

# This file is generated by GoReleaser. DO NOT EDIT.
class Diffpane < Formula
  desc "Real-time TUI diff viewer for AI coding agents"
  homepage "https://github.com/Astro-Han/diffpane"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Astro-Han/diffpane/releases/download/v0.2.0/diffpane_0.2.0_darwin_amd64.tar.gz"
      sha256 "9eaf921501eba4a4d26931c1746290274ec390cbfe3b41467081e527bb1b6560"
    end

    on_arm do
      url "https://github.com/Astro-Han/diffpane/releases/download/v0.2.0/diffpane_0.2.0_darwin_arm64.tar.gz"
      sha256 "bafa8dfa9a91f0aacd1202a8ca7a9dfc30f5d1777c9db817ba54fd72cc37aa92"
    end
  end

  def install
    bin.install "diffpane"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/diffpane --version 2>&1", 1)
  end
end
